//
// Created by User on 2021-11-24.
//

#ifndef CLOUDCAMERA_COMMONCONSTANT_H
#define CLOUDCAMERA_COMMONCONSTANT_H

#define DTYPE_UINT8 0
#define DTYPE_INT8 1
#define DTYPE_FLOAT 2

#endif //CLOUDCAMERA_COMMONCONSTANT_H
