/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_ac_snu_nxc_cloudcamera_library_ImageUtils */

#ifndef _Included_kr_ac_snu_nxc_cloudcamera_library_ImageUtils
#define _Included_kr_ac_snu_nxc_cloudcamera_library_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef kr_ac_snu_nxc_cloudcamera_library_ImageUtils_YUV_CHANNEL
#define kr_ac_snu_nxc_cloudcamera_library_ImageUtils_YUV_CHANNEL 0L
#undef kr_ac_snu_nxc_cloudcamera_library_ImageUtils_Y_CHANNEL
#define kr_ac_snu_nxc_cloudcamera_library_ImageUtils_Y_CHANNEL 1L
#undef kr_ac_snu_nxc_cloudcamera_library_ImageUtils_UV_CHANNEL
#define kr_ac_snu_nxc_cloudcamera_library_ImageUtils_UV_CHANNEL 2L
#undef kr_ac_snu_nxc_cloudcamera_library_ImageUtils_MAX_IMAGE_BUFFERS
#define kr_ac_snu_nxc_cloudcamera_library_ImageUtils_MAX_IMAGE_BUFFERS 10L
#undef kr_ac_snu_nxc_cloudcamera_library_ImageUtils_DIFF_METHOD_SIMPLE
#define kr_ac_snu_nxc_cloudcamera_library_ImageUtils_DIFF_METHOD_SIMPLE 0L
#undef kr_ac_snu_nxc_cloudcamera_library_ImageUtils_DIFF_METHOD_MSE
#define kr_ac_snu_nxc_cloudcamera_library_ImageUtils_DIFF_METHOD_MSE 1L
#undef kr_ac_snu_nxc_cloudcamera_library_ImageUtils_DIFF_METHOD_PSNR
#define kr_ac_snu_nxc_cloudcamera_library_ImageUtils_DIFF_METHOD_PSNR 2L
/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    convertBitmapNative
 * Signature: (Landroid/graphics/Bitmap;Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_convertBitmapNative
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    convertYuvNative
 * Signature: (Ljava/nio/ByteBuffer;Landroid/graphics/Bitmap;III)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_convertYuvNative
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    convertResizedBitmapNative
 * Signature: (Landroid/graphics/Bitmap;Ljava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_convertResizedBitmapNative
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    downScaleCCImage
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_downScaleCCImage
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    swapUV
 * Signature: (Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_swapUV
        (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    computePixelDiff
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)F
 */
JNIEXPORT jfloat JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_computePixelDiff
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    convertCenterCropCCImage
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIIIII)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_convertCenterCropCCImage
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    convertByteToFloatBuffer
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIZ)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_convertByteToFloatBuffer
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jboolean);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    convertFloatToByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIIZ)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_convertFloatToByteBuffer
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jboolean);

JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_nativeMergeImages
        (JNIEnv *, jclass, jobjectArray, jobject, jint, jint, jint, jboolean);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    convertByteToFloatBufferArray
 * Signature: ([Ljava/nio/ByteBuffer;Ljava/nio/FloatBuffer;IIIZ)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_convertByteToFloatBufferArray
        (JNIEnv *, jclass, jobjectArray, jobject, jint, jint, jint, jboolean);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    convertFloatToBitmap
 * Signature: (Landroid/graphics/Bitmap;Ljava/nio/ByteBuffer;IIZ)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_convertFloatToBitmap
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jboolean);

/*
 * Class:     kr_ac_snu_nxc_cloudcamera_library_ImageUtils
 * Method:    updateCCImage
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIIIZ)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_updateCCImage
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint, jboolean);

JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_nativeQuantizeBuffer
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jfloat, jint);

JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_nativeGetLatentBitmap
        (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint, jobject, jfloat, jint);

JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_nativeSubtractBuffer
        (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint, jint);

JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_nativeMergeBuffer
        (JNIEnv *, jclass, jobject, jobjectArray, jint, jint, jint, jint);

JNIEXPORT void JNICALL Java_kr_ac_snu_nxc_cloudcamera_library_ImageUtils_nativeMergeBufferChannel
        (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
